---
version: '2.1'

services:
  performance-test:
    build:
      context: .
#    image: docker.artifactory.reform.hmcts.net/evidence/performance-tests:latest
    environment:
      - DM_BASE_URI=http://document-management-store-api-gateway-web:8080
      - IDAM_USER_BASE_URI=http://idam-api:8080
      - IDAM_S2S_BASE_URI=http://service-auth-provider-api:8080
    links:
      - document-management-store-api-gateway-web
      - idam-api
      - service-auth-provider-api
    depends_on:
      - document-management-store-api-gateway-web
      - idam-api
      - service-auth-provider-api
